title: Great Outdoors
description: >
    Poul Nichols' Great Outdoors is a travel blog featuring parks, trails, and
    other outdoor destinations throughout the Pacific Northwest.
baseurl: "/GreatOutdoors/" # the subpath of your site, e.g. /blog/
url: "http://shorian.github.io"

exclude:
  - README.md
  - TeamCharter.md
  - LICENSE
  - template.html
  - homepage_screenshot.png
