---
name: Prettier and Linter

on: push

permissions:
  contents: write
  statuses: write

jobs:
  prettier-and-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{html,css,js}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        uses: super-linter/super-linter@v7.3.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
